// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kutuphane.Data;

#nullable disable

namespace kutuphane.Migrations
{
    [DbContext(typeof(KutuphaneDbContext))]
    [Migration("20260128080145_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("kutuphane.Models.Kitap", b =>
                {
                    b.Property<int>("kitapNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("kitapNo"));

                    b.Property<string>("ISBNNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("kitapAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("kitapOzeti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("sayfaSayisi")
                        .HasColumnType("int");

                    b.HasKey("kitapNo");

                    b.ToTable("Kitap", (string)null);
                });

            modelBuilder.Entity("kutuphane.Models.KitapTur", b =>
                {
                    b.Property<int>("kitapNo")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("turNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("kitapNo", "turNo");

                    b.HasIndex("turNo");

                    b.ToTable("kitap_tur", (string)null);
                });

            modelBuilder.Entity("kutuphane.Models.KitapYazar", b =>
                {
                    b.Property<int>("kitap_yazarNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("kitap_yazarNo"));

                    b.Property<int>("kitapNo")
                        .HasColumnType("int");

                    b.Property<int>("yazarNo")
                        .HasColumnType("int");

                    b.HasKey("kitap_yazarNo");

                    b.HasIndex("kitapNo");

                    b.HasIndex("yazarNo");

                    b.ToTable("kitap_yazar", (string)null);
                });

            modelBuilder.Entity("kutuphane.Models.Odunc", b =>
                {
                    b.Property<int>("oduncNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("oduncNo"));

                    b.Property<bool>("geldiMi")
                        .HasColumnType("bit");

                    b.Property<int>("kitapNo")
                        .HasColumnType("int");

                    b.Property<int>("uyeNo")
                        .HasColumnType("int");

                    b.Property<int>("vermeSuresi")
                        .HasColumnType("int");

                    b.Property<DateTime>("vermeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("oduncNo");

                    b.HasIndex("kitapNo");

                    b.HasIndex("uyeNo");

                    b.ToTable("odunc", (string)null);
                });

            modelBuilder.Entity("kutuphane.Models.Tur", b =>
                {
                    b.Property<int>("turNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("turNo"));

                    b.Property<string>("turAciklama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("turNo");

                    b.ToTable("tur", (string)null);
                });

            modelBuilder.Entity("kutuphane.Models.Uye", b =>
                {
                    b.Property<int>("uyeNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("uyeNo"));

                    b.Property<string>("adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("adresi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("aktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("soyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("uyeNo");

                    b.ToTable("uye", (string)null);
                });

            modelBuilder.Entity("kutuphane.Models.Yazar", b =>
                {
                    b.Property<int>("yazarNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("yazarNo"));

                    b.Property<string>("adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("dogum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("hayatOzeti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("yazarNo");

                    b.ToTable("yazar", (string)null);
                });

            modelBuilder.Entity("kutuphane.Models.KitapTur", b =>
                {
                    b.HasOne("kutuphane.Models.Kitap", "Kitap")
                        .WithMany("KitapTurler")
                        .HasForeignKey("kitapNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kutuphane.Models.Tur", "Tur")
                        .WithMany("KitapTurler")
                        .HasForeignKey("turNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Tur");
                });

            modelBuilder.Entity("kutuphane.Models.KitapYazar", b =>
                {
                    b.HasOne("kutuphane.Models.Kitap", "Kitap")
                        .WithMany("KitapYazarlar")
                        .HasForeignKey("kitapNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kutuphane.Models.Yazar", "Yazar")
                        .WithMany("KitapYazarlar")
                        .HasForeignKey("yazarNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Yazar");
                });

            modelBuilder.Entity("kutuphane.Models.Odunc", b =>
                {
                    b.HasOne("kutuphane.Models.Kitap", "Kitap")
                        .WithMany("Oduncler")
                        .HasForeignKey("kitapNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kutuphane.Models.Uye", "Uye")
                        .WithMany("Oduncler")
                        .HasForeignKey("uyeNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("kutuphane.Models.Kitap", b =>
                {
                    b.Navigation("KitapTurler");

                    b.Navigation("KitapYazarlar");

                    b.Navigation("Oduncler");
                });

            modelBuilder.Entity("kutuphane.Models.Tur", b =>
                {
                    b.Navigation("KitapTurler");
                });

            modelBuilder.Entity("kutuphane.Models.Uye", b =>
                {
                    b.Navigation("Oduncler");
                });

            modelBuilder.Entity("kutuphane.Models.Yazar", b =>
                {
                    b.Navigation("KitapYazarlar");
                });
#pragma warning restore 612, 618
        }
    }
}
